### ISSUE TITLE
安卓下登录有问题。

### ISSUE THREAD

**Issue by happyming9527** [reactnativecn/react-native-wx#2]
在ios下面没有问题。但是安卓下，微信授权界面打开后，点击授权，没有返回数据。分享功能中，发送给朋友文字信息，能打开微信的界面，但是点击朋友后，发送界面一闪而过，不能发出去。请问是什么原因？

**Comment by happyming9527** [comment]
logcat 输出如下

I/System.out(26697): [socket][8] connection open.weixin.qq.com/140.207.62.51:443;LocalPort=40701(10000)
I/System.out(26697): [CDS]connect[open.weixin.qq.com/140.207.62.51:443] tm:10
I/System.out(26697): [socket][/192.168.200.101:40701] connected
I/System.out(26697): [CDS]rx timeout:0
I/System.out(26697): [CDS]SO_SNDBUF:24576
W/System.err(26697): java.lang.NullPointerException: Attempt to invoke virtual method 'boolean com.tencent.smtt.webkit.WebViewClassic.isMiniQB()' on a null object reference
W/System.err(26697):    at com.tencent.smtt.net.http.v.c(TbsCoreJava:2821)
W/System.err(26697):    at com.tencent.smtt.net.http.v.b(TbsCoreJava:2747)
W/System.err(26697):    at com.tencent.smtt.net.http.e.a(TbsCoreJava:641)
W/System.err(26697):    at com.tencent.smtt.net.http.h.run(TbsCoreJava:192)
I/System.out(26697): [CDS]close[40701]

**Comment by lqs6910** [comment]
我在android上微信分享也是能打开微信，选择朋友后页面一闪而过，没有发送出去。

**Comment by tdzl2003** [comment]
通常这都是配置问题，微信SDK植入的过程较为繁琐，请严格按照文档进行，并确保包名和签名与应用平台上的一致。

**Comment by happyming9527** [comment]
包名的配置的确有点问题。不过修复后，还是有一样的问题。logcat的报错有变化了，请帮忙看看是什么原因？

E/TbsSDKExtension(16564): tbslog exceptions:java.lang.ClassNotFoundException: com.tencent.smtt.utils.TbsLog
E/TbsSDKExtension(16564):   at java.lang.Class.classForName(Native Method)
E/TbsSDKExtension(16564):   at java.lang.Class.forName(Class.java:308)
E/TbsSDKExtension(16564):   at java.lang.Class.forName(Class.java:272)
E/TbsSDKExtension(16564):   at com.tencent.tbs.sdk.extension.i.a(TbsSdkExtension:78)
E/TbsSDKExtension(16564):   at com.tencent.tbs.sdk.extension.i.a(TbsSdkExtension:62)
E/TbsSDKExtension(16564):   at com.tencent.tbs.sdk.extension.i.b(TbsSdkExtension:19)
E/TbsSDKExtension(16564):   at com.tencent.tbs.sdk.extension.TbsSDKExtension.realExecuteCommand(TbsSdkExtension:1074)
E/TbsSDKExtension(16564):   at com.tencent.tbs.sdk.extension.TbsSDKExtension$3.run(TbsSdkExtension:1059)
E/TbsSDKExtension(16564):   at java.lang.Thread.run(Thread.java:831)
E/TbsSDKExtension(16564): Caused by: java.lang.ClassNotFoundException: Didn't find class "com.tencent.smtt.utils.TbsLog" on path: DexPathList[[zip file "/data/data/com.tencent.mm/app_tbs/core_share/tbs_sdk_extension_dex.jar"],nativeLibraryDirectories=[/vendor/lib, /system/lib]]
E/TbsSDKExtension(16564):   at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
E/TbsSDKExtension(16564):   at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
E/TbsSDKExtension(16564):   at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
E/TbsSDKExtension(16564):   ... 9 more
E/TbsSDKExtension(16564):   Suppressed: java.lang.ClassNotFoundException: Didn't find class "com.tencent.smtt.utils.TbsLog" on path: DexPathList[[zip file "/data/data/com.tencent.mm/app_dex/4825a05a-patch.apk", zip file "/data/data/com.tencent.mm/app_dex/secondary-1.dex.jar", zip file "/data/data/com.tencent.mm/app_dex/secondary-2.dex.jar", zip file "/data/data/com.tencent.mm/app_dex/secondary-3.dex.jar", zip file "/system/framework/com.google.android.maps.jar", zip file "/data/app/com.tencent.mm-2/base.apk"],nativeLibraryDirectories=[/data/app/com.tencent.mm-2/lib/arm, /vendor/lib, /system/lib]]
E/TbsSDKExtension(16564):       at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
E/TbsSDKExtension(16564):       at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
E/TbsSDKExtension(16564):       at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
E/TbsSDKExtension(16564):       ... 10 more
E/TbsSDKExtension(16564):       Suppressed: java.lang.ClassNotFoundException: com.tencent.smtt.utils.TbsLog
E/TbsSDKExtension(16564):           at java.lang.Class.classForName(Native Method)
E/TbsSDKExtension(16564):           at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
E/TbsSDKExtension(16564):           at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
E/TbsSDKExtension(16564):           at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
E/TbsSDKExtension(16564):           ... 11 more
E/TbsSDKExtension(16564):       Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack available

**Comment by StarksJohn** [comment]
LoginWXApp(){
    WechatAPI.login({ scope: 'snsapi_userinfo', state: '123' }).
    then( function (result) {
        ToastAndroid.show('登录成功==' + result, ToastAndroid.LONG);

```
} ,function (fail) {
    ToastAndroid.show('登录失败==' + fail, ToastAndroid.LONG);

} ).catch ( function (e) {
    ToastAndroid.show('登录失败,捕获到错误==' + e.message, ToastAndroid.LONG);

} );
```

  }

为何我没看到 显示 Toast, 能进到 授权页,然后点击 授权按钮后就返回了 原来页面

**Comment by nanasheng** [comment]
按文档操作的，不能实现登录，菜鸟求助

**Comment by ykl522** [comment]
@cham1985 
我把源码里的回调改成了这样
export function pay(data,msgBack,errBack) {
  return nativePayRequest(data)
      .then(() => waitForResponse("Pay.Resp").then(msgBack,errBack));
}

**Comment by liusanhong** [comment]
请问下，支付功能是不是ok。是用的RN的ping++么，网址可否给一下

**Comment by Uwingame** [comment]
@liusanhong 我没用它的支付功能.我用了ping++的支付.
